version: '3'
services:
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
      
  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092

  payment:
    image: coc/payment-integ:latest
    ports:
     - 8080:8080
    depends_on:
     - cassandra
     - kafka
    command: ["cassandra", "9042", "java -Dspring.profiles.active=prod -jar app.jar"]