apiVersion: v1
kind: Service
metadata:
   name: kafka
spec:
   selector:
     app: kafka-deployment
   type: {{ .Values.service.type }}
   ports:
   - name: kafka
     protocol: TCP
     port: 9092 
---
apiVersion: v1
kind: Service
metadata:
   name: demo-app
spec:
   selector:
     app: demo-app-deployment
   type: {{ .Values.service.type }}
   ports:
   - name: api
     protocol: TCP
     port: 8080