/*
 * This file is generated by jOOQ.
 */
package com.sapient.learning.data.public_;


import com.sapient.learning.data.public_.tables.Author;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final Author AUTHOR = com.sapient.learning.data.public_.tables.Author.AUTHOR;
}
